version: "3"

services:
  rails:
    build:
      context: ./rails
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '2722:2722'
    volumes:
      - ./rails:/app
    stdin_open: true
    environment:
      - RAILS_ENV=test
      - RAILS_DB_NAME=workbooker_api_test
      - RAILS_DB_USER=xaragne
      - RAILS_DB_HOST=db
      - RAILS_DB_PORT=5432
      - RAILS_DB_PASSWORD=xaragne
      - RAILS_APP_PORT=2722

  db:
    image: postgres:13.0
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
      - .:/app
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=workbooker_api_development
      - POSTGRES_USER=xaragne
      - POSTGRES_PASSWORD=xaragne

  redis:
    image: k8s.gcr.io/redis:e2e
    ports:
      - "6379"

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
  rails:
