default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["TMG_DATABASE_PASSWORD"] %>
  user: <%= ENV["TMG_DATABASE_USER"] %>
  database: <%= ENV["TMG_DATABASE_NAME"] %>
  host: <%= ENV["TMG_DATABASE_HOST"] %>
  port: <%= ENV["TMG_DATABASE_PORT"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
